### ISSUE TITLE
dml error on package containing 'external'

### ISSUE THREAD

**Issue by pedrorijo91** [fenix-framework/fenix-framework#200]
The following .dml file gets an error:

    package org.fenixedu.external.users.domain;

This error is not observed if 'external' is removed:

    package org.fenixedu.users.domain;

Stacktrace:

    Exception in thread "main" java.lang.Error: line 1:22: expecting IDENT, found 'external'
	at pt.ist.fenixframework.DomainModelParser.getDomainModel(DomainModelParser.java:54)
	at pt.ist.fenixframework.DmlCompiler.getDomainModel(DmlCompiler.java:56)
	at pt.ist.fenixframework.DmlCompiler.compile(DmlCompiler.java:41)
	at pt.ist.fenixframework.dml.maven.AbstractDmlCodeGeneratorMojo.execute(AbstractDmlCodeGeneratorMojo.java:166)
	at pt.ist.fenixframework.dml.maven.DmlCodeGeneratorMojo.execute(DmlCodeGeneratorMojo.java:101)
	at pt.ist.fenixframework.maven.FFDmlCodeGeneratorMojo.execute(FFDmlCodeGeneratorMojo.java:111)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

    Caused by: line 1:22: expecting IDENT, found 'external'
	at antlr.Parser.match(Parser.java:211)
	at pt.ist.fenixframework.dml.DmlParser.identifier(DmlParser.java:429)
	at pt.ist.fenixframework.dml.DmlParser.packageDeclaration(DmlParser.java:262)
	at pt.ist.fenixframework.dml.DmlParser.domainDefinition(DmlParser.java:129)
	at pt.ist.fenixframework.dml.DmlParser.domainDefinitions(DmlParser.java:72)
	at pt.ist.fenixframework.DomainModelParser.getDomainModel(DomainModelParser.java:49)
	... 26 more

**Comment by jcarvalho** [comment]
This issue also seems to occur with the keywords `enum`, `valueType`, `as`, `externalizeWith`, `internalizeWith`, `package`, `class`, `extends`, `implements`, `public`, `protected`, `REQUIRED`, `relation`, `playsRole`, `multiplicity`, `indexed`, `ordered`.

Some of these keywords are already not allowed in Java, but it should be possible to use them in the DML.
